# -*- mode: python ; coding: utf-8 -*-

import os

# Get the project root directory
project_root = os.path.abspath('.')

# Data files to include
datas = [
    ('haarcascade_frontalface_default.xml', '.'),
    # Replicate paketini data olarak da ekle
    ('replicate', 'replicate'),
]

# Hidden imports
hiddenimports = [
    'cv2',
    'PIL',
    'numpy',
    'requests',
    'tkinter',
    'tkinter.filedialog',
    'tkinter.messagebox',
    'tkinter.ttk',
    'replicate',
    'replicate.__about__',
    'replicate.__init__',
    'replicate.account',
    'replicate.client',
    'replicate.collection',
    'replicate.deployment',
    'replicate.exceptions',
    'replicate.file',
    'replicate.hardware',
    'replicate.helpers',
    'replicate.identifier',
    'replicate.model',
    'replicate.pagination',
    'replicate.prediction',
    'replicate.resource',
    'replicate.run',
    'replicate.schema',
    'replicate.stream',
    'replicate.training',
    'replicate.version',
    'replicate.webhook',
    'replicate.api',
    'replicate.api_operations',
    'replicate.api_resources',
    'replicate.types',
    'replicate.utils',
    'importlib.metadata',
    'importlib.metadata._adapters',
    'importlib.metadata._collections',
    'importlib.metadata._compat',
    'importlib.metadata._functools',
    'importlib.metadata._itertools',
    'importlib.metadata._meta',
    'importlib.metadata._text',
    'importlib.metadata._typing',
    'importlib.metadata._zip',
    'pkg_resources',
    'setuptools',
    'packaging',
    'packaging.version',
    'packaging.specifiers',
    'packaging.requirements',
    'urllib3',
    'urllib3.util',
    'urllib3.util.retry',
    'urllib3.util.timeout',
    'urllib3.poolmanager',
    'urllib3.connectionpool',
    'urllib3.response',
    'urllib3.exceptions',
    'certifi',
    'charset_normalizer',
    'idna',
    'typing_extensions',
    'pydantic',
    'pydantic_core',
    'annotated_types',
    'email_validator',
    'httpx',
    'anyio',
    'sniffio',
    'h11',
    'h2',
    'hpack',
    'hyperframe',
    'hstspreload',
    'brotli',
    'brotlicffi',
    'cryptography',
    'cffi',
    'pycparser',
    'pydantic',
    'pydantic_core',
    'annotated_types',
    'email_validator',
    'httpx',
    'anyio',
    'sniffio',
    'h11',
    'h2',
    'hpack',
    'hyperframe',
    'hstspreload',
    'brotli',
    'brotlicffi',
    'urllib3',
    'urllib3.util',
    'urllib3.util.retry',
    'urllib3.util.timeout',
    'urllib3.poolmanager',
    'urllib3.connectionpool',
    'urllib3.response',
    'urllib3.exceptions',
    'certifi',
    'charset_normalizer',
    'idna',
    'typing_extensions',
]

a = Analysis(
    ['desktop_app.py'],
    pathex=[project_root],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='BiyoVes',
    icon=os.path.join(project_root, 'appicon.icns'),
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    onefile=False,  # Use onedir mode
)