name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        # PySide6 DLL'lerinin doğru yüklenmesi için
        pip uninstall -y PySide6 shiboken6
        pip install --no-cache-dir PySide6
        # PySide6 DLL'lerinin PATH'e eklenmesi
        echo "$((Get-Command python).Path | Split-Path)\Lib\site-packages\PySide6" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Verify files exist
      run: |
        echo "Checking required files..."
        if (Test-Path "desktop_app.py") { echo "✓ desktop_app.py found" } else { echo "✗ desktop_app.py missing"; exit 1 }
        if (Test-Path "haarcascade_frontalface_default.xml") { echo "✓ haarcascade file found" } else { echo "✗ haarcascade file missing"; exit 1 }
        echo "Skipping MODNet checkpoint check (now using Replicate API)"
        if (Test-Path "pyinstaller.spec") { echo "✓ pyinstaller.spec found" } else { echo "✗ pyinstaller.spec missing"; exit 1 }

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --clean --log-level DEBUG pyinstaller.spec

    - name: Check build output
      run: |
        echo "Build output structure:"
        if (Test-Path "dist") {
          Get-ChildItem -Path "dist" -Recurse | Format-Table -AutoSize
        } else {
          echo "✗ dist folder not found"; exit 1
        }
        $dirOk = Test-Path "dist\BiyoVes"
        $exeOk = Test-Path "dist\BiyoVes.exe"
        if (-not $dirOk -and -not $exeOk) {
          echo "✗ Neither dist\\BiyoVes directory nor dist\\BiyoVes.exe exists"; exit 1
        }

    - name: Upload artifact (handles dir or exe)
      uses: actions/upload-artifact@v4
      with:
        name: BiyoVes-Windows
        path: |
          dist/BiyoVes
          dist/BiyoVes.exe
        if-no-files-found: warn
