name: Build Windows EXE
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka
          pip install --no-cache-dir --force-reinstall PySide6
      
      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64" -y
          choco install windows-sdk-10.0 -y
      
      - name: Verify files exist
        run: |
          echo "Checking required files..."
          if (Test-Path "desktop_app.py") { echo "✓ desktop_app.py found" } else { echo "✗ desktop_app.py missing"; exit 1 }
          if (Test-Path "haarcascade_frontalface_default.xml") { echo "✓ haarcascade file found" } else { echo "✗ haarcascade file missing"; exit 1 }
          if (Test-Path "appicon.ico") { echo "✓ appicon.ico found" } else { echo "⚠ appicon.ico missing - build will continue without icon" }
          echo "Using Replicate API (no MODNet checkpoint needed)"
      
      - name: Build with Nuitka
        run: |
          $iconParam = if (Test-Path "appicon.ico") { "--windows-icon-from-ico=appicon.ico" } else { "" }
          python -m nuitka `
            --standalone `
            --onefile `
            --enable-plugin=pyside6 `
            --follow-imports `
            $iconParam `
            --include-data-files=haarcascade_frontalface_default.xml=haarcascade_frontalface_default.xml `
            --include-package=cv2 `
            --include-package=PIL `
            --include-package=numpy `
            --include-package=requests `
            --include-package=replicate `
            --windows-console-mode=disable `
            --company-name="BiyoVes" `
            --product-name="BiyoVes" `
            --file-version="1.0.0.0" `
            --product-version="1.0.0" `
            --file-description="BiyoVes Biometric Verification System" `
            desktop_app.py
      
      - name: Check build output
        run: |
          echo "Build output structure:"
          Get-ChildItem -Path "desktop_app.dist" -Recurse | Format-Table -AutoSize
      
      - name: Create release package
        run: |
          New-Item -ItemType Directory -Force -Path "release"
          Copy-Item -Path "desktop_app.dist\*" -Destination "release\" -Recurse
          if (Test-Path "README.md") { Copy-Item "README.md" "release\" }
          Compress-Archive -Path "release\*" -DestinationPath "BiyoVes-Windows.zip"
      
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: BiyoVes-Windows-EXE
          path: desktop_app.dist/desktop_app.exe
          if-no-files-found: error
      
      - name: Upload full package
        uses: actions/upload-artifact@v4
        with:
          name: BiyoVes-Windows-Full
          path: BiyoVes-Windows.zip
          if-no-files-found: error