name: Windows EXE Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install torch==2.3.1+cpu torchvision==0.18.1+cpu --index-url https://download.pytorch.org/whl/cpu
          pip install pyinstaller==6.9.0

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --noconfirm pyinstaller.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BiyoVes-windows
          path: dist/BiyoVes/**
