name: build-windows-exe

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Ensure MODNet pretrained exists
        shell: pwsh
        run: |
          $modelPath = Join-Path $env:GITHUB_WORKSPACE "MODNet\pretrained\modnet_photographic_portrait_matting.ckpt"
          if (!(Test-Path $modelPath)) {
            New-Item -ItemType Directory -Force -Path (Split-Path $modelPath) | Out-Null
            Write-Host "Model checkpoint not found at $modelPath"
            Write-Host "If you use Git LFS, ensure the file is tracked and available."
            Write-Host "Alternatively, add a download step to fetch the checkpoint."
            exit 1
          }

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller (spec)
        shell: pwsh
        working-directory: ${{ github.workspace }}
        run: pyinstaller --noconfirm .\pyinstaller.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BiyoVes-windows
          path: dist/BiyoVes
